-- Sentiment Analysis Logs Table
-- Run this in your Supabase SQL Editor

CREATE TABLE IF NOT EXISTS sentiment_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text TEXT NOT NULL,
  sentiment TEXT NOT NULL,
  confidence FLOAT NOT NULL,
  reason TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
